name: Tag-Release

on:
  schedule:
  - cron: 0 17 1 * *
  workflow_dispatch: {}

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

    - name: Tag new release name
      run: |
        export TAG="$(date +"v%Y%m%d")"
        git tag "${TAG}"
        git push origin "${TAG}"
